%YAML:1.0
#--------------------------------------------------------------------------------------------
# 相机参数，请根据实际情况调整！
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"  # 相机模型类型，"PinHole" 为针孔模型，常用于普通相机

# 相机标定和畸变参数（OpenCV）
Camera.fx: 1034.612816   # 517.306408 × 2，X轴焦距（像素）
Camera.fy: 1032.938430   # 516.469215 × 2，Y轴焦距（像素）
Camera.cx: 637.286080    # 318.643040 × 2，主点X坐标（像素）
Camera.cy: 510.627978    # 255.313989 × 2，主点Y坐标（像素）

Camera.k1: 0.262383     # 相机的径向畸变参数 k1
Camera.k2: -0.953104    # 相机的径向畸变参数 k2
Camera.p1: -0.005358    # 相机的切向畸变参数 p1
Camera.p2: 0.002628     # 相机的切向畸变参数 p2
Camera.k3: 1.163314     # 相机的径向畸变参数 k3

# 相机每秒帧数
Camera.fps: 30.0        # 每秒钟的帧数，影响图像更新速度

# 图像的颜色通道顺序（0: BGR，1: RGB。若图像为灰度图，则忽略此项）
Camera.RGB: 1           # 图像颜色顺序，1表示RGB，0表示BGR

# 相机分辨率（调整为两倍）
Camera.width: 1280       # 图像宽度（像素），原640×2
Camera.height: 960       # 图像高度（像素），原480×2

#--------------------------------------------------------------------------------------------
# ORB特征提取器参数
#--------------------------------------------------------------------------------------------

# ORB 提取器：每张图像提取的最大特征点数量
ORBextractor.nFeatures: 1500  # 每张图像最多提取的特征点数量

# ORB 提取器：尺度金字塔每层之间的缩放因子
ORBextractor.scaleFactor: 1.1  # 每个尺度层级之间的大小缩放因子，控制金字塔的尺度分辨率

# ORB 提取器：尺度金字塔的层数
ORBextractor.nLevels: 6       # 图像尺度金字塔的层数，决定了提取特征点时所考虑的尺度范围

# ORB 提取器：FAST特征点检测的阈值
# 图像被分割成网格，在每个网格内使用FAST检测角点，采用一个最低响应值作为判断标准。
# 如果未检测到特征点，则使用更低的阈值进行重新检测
ORBextractor.iniThFAST: 15   # FAST特征的初始化阈值，决定角点检测的灵敏度
ORBextractor.minThFAST: 5    # FAST特征的最小阈值，角点的响应值小于此值时会被舍弃

#--------------------------------------------------------------------------------------------
# 视觉效果参数
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05     # 关键帧的大小（单位：相机坐标系的单位）
Viewer.KeyFrameLineWidth: 1   # 关键帧线条的宽度，影响显示时线条的粗细
Viewer.GraphLineWidth: 0.9    # 关键帧之间连接线的宽度
Viewer.PointSize: 2           # 显示图像中的点的大小
Viewer.CameraSize: 0.08       # 显示相机图标的大小
Viewer.CameraLineWidth: 3     # 相机图标的线条宽度
Viewer.ViewpointX: 0          # 视角的X坐标，影响观察场景时的视角位置
Viewer.ViewpointY: -0.7      # 视角的Y坐标，影响观察场景时的视角位置
Viewer.ViewpointZ: -1.8      # 视角的Z坐标，影响观察场景时的视角位置
Viewer.ViewpointF: 500       # 视角的焦距，决定观察场景时的视野范围
